services:
  - type: web
    name: ai-restaurant-recommendation-system
    env: python
    runtime: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install --only-binary=all -r requirements-minimal.txt
    startCommand: ./start.sh
    plan: free
    envVars:
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: false
